package es.vinhnb.ttht.entity.api;

import com.google.gson.annotations.SerializedName;

/**
 * Created by VinhNB on 11/22/2017.
 */

public class MTBModelNew {
    //CHUNG
    //TODO bien ban
    @SerializedName("ID_BBAN_CONGTO")
    public int ID_BBAN_CONGTO;
    @SerializedName("MA_DVIQLY")
    public String MA_DVIQLY;
    @SerializedName("SO_BBAN")
    public String SO_BBAN;
    @SerializedName("TRANG_THAI")
    public int TRANG_THAI;
    @SerializedName("LAN_CTO_TREO")

    //TODO cong to treo
    public int LAN_CTO_TREO;
    @SerializedName("VTRI_TREO_THAO_CTO_TREO")
    public int VTRI_TREO_THAO_CTO_TREO;
    @SerializedName("SOVIEN_CBOOC_CTO_TREO")
    public int SOVIEN_CBOOC_CTO_TREO;
    @SerializedName("LOAI_HOM_CTO_TREO")
    public int LOAI_HOM_CTO_TREO;
    @SerializedName("SOVIEN_CHOM_CTO_TREO")
    public int SOVIEN_CHOM_CTO_TREO;
    @SerializedName("HS_NHAN_CTO_TREO")
    public int HS_NHAN_CTO_TREO;
    @SerializedName("SO_TU_CTO_TREO")
    public String SO_TU_CTO_TREO;
    @SerializedName("SO_TI_CTO_TREO")
    public String SO_TI_CTO_TREO;
    @SerializedName("CHI_SO_CTO_TREO")
    public String CHI_SO_CTO_TREO;
    @SerializedName("CCX_CTO_TREO")
    public int CCX_CTO_TREO;
    @SerializedName("TEM_CQUANG_CTO_TREO")
    public String TEM_CQUANG_CTO_TREO;
    @SerializedName("SOVIEN_CHIKDINH_CTO_TREO")
    public int SOVIEN_CHIKDINH_CTO_TREO;
    @SerializedName("DIEN_AP_CTO_TREO")
    public String DIEN_AP_CTO_TREO;
    @SerializedName("DONG_DIEN_CTO_TREO")
    public String DONG_DIEN_CTO_TREO;
    @SerializedName("HANGSO_K_CTO_TREO")
    public String HANGSO_K_CTO_TREO;
    @SerializedName("SO_KIM_NIEM_CHI_CTO_TREO")
    public String SO_KIM_NIEM_CHI_CTO_TREO;
    @SerializedName("TTRANG_NPHONG_CTO_TREO")
    public String TTRANG_NPHONG_CTO_TREO;
    @SerializedName("TEN_LOAI_CTO_CTO_TREO")
    public String TEN_LOAI_CTO_CTO_TREO;
    @SerializedName("PHUONG_THUC_DO_XA_CTO_TREO")
    public String PHUONG_THUC_DO_XA_CTO_TREO;
    @SerializedName("GHI_CHU_CTO_TREO")
    public String GHI_CHU_CTO_TREO;

    //TODO cong to thao
    @SerializedName("LAN_CTO_THAO")
    public int LAN_CTO_THAO;
    @SerializedName("VTRI_TREO_THAO_CTO_THAO")
    public int VTRI_TREO_THAO_CTO_THAO;
    @SerializedName("SOVIEN_CBOOC_CTO_THAO")
    public int SOVIEN_CBOOC_CTO_THAO;
    @SerializedName("LOAI_HOM_CTO_THAO")
    public int LOAI_HOM_CTO_THAO;
    @SerializedName("SOVIEN_CHOM_CTO_THAO")
    public int SOVIEN_CHOM_CTO_THAO;
    @SerializedName("HS_NHAN_CTO_THAO")
    public int HS_NHAN_CTO_THAO;
    @SerializedName("SO_TU_CTO_THAO")
    public String SO_TU_CTO_THAO;
    @SerializedName("SO_TI_CTO_THAO")
    public String SO_TI_CTO_THAO;
    @SerializedName("CHI_SO_CTO_THAO")
    public String CHI_SO_CTO_THAO;
    @SerializedName("CCX_CTO_THAO")
    public int CCX_CTO_THAO;
    @SerializedName("TEM_CQUANG_CTO_THAO")
    public String TEM_CQUANG_CTO_THAO;
    @SerializedName("SOVIEN_CHIKDINH_CTO_THAO")
    public int SOVIEN_CHIKDINH_CTO_THAO;
    @SerializedName("DIEN_AP_CTO_THAO")
    public String DIEN_AP_CTO_THAO;
    @SerializedName("DONG_DIEN_CTO_THAO")
    public String DONG_DIEN_CTO_THAO;
    @SerializedName("HANGSO_K_CTO_THAO")
    public String HANGSO_K_CTO_THAO;
    @SerializedName("SO_KIM_NIEM_CHI_CTO_THAO")
    public String SO_KIM_NIEM_CHI_CTO_THAO;
    @SerializedName("TTRANG_NPHONG_CTO_THAO")
    public String TTRANG_NPHONG_CTO_THAO;
    @SerializedName("TEN_LOAI_CTO_CTO_THAO")
    public String TEN_LOAI_CTO_CTO_THAO;
    @SerializedName("PHUONG_THUC_DO_XA_CTO_THAO")
    public String PHUONG_THUC_DO_XA_CTO_THAO;
    @SerializedName("GHI_CHU_CTO_THAO")
    public String GHI_CHU_CTO_THAO;


    //TODO update bang DU_LIEU_HIEN_TRUONG
    ////TODO anh chu ki KH
    // @SerializedName("TEN_ANH_CHU_KI")
    //public String TEN_ANH_CHU_KI;
    // @SerializedName("ANH_CHU_KI")
    //public String ANH_CHU_KI;

    //TODO anh Cong To Treo
    @SerializedName("ID_BBAN_TUTI_CTO_TREO")
    public int ID_BBAN_TUTI_CTO_TREO;
    @SerializedName("ID_CHITIET_TUTI_TU_CTO_TREO")
    public int ID_CHITIET_TUTI_TU_CTO_TREO;

    //anh cong to
    @SerializedName("ID_CHITIET_TUTI_TI_CTO_TREO")
    public int ID_CHITIET_TUTI_TI_CTO_TREO;

    @SerializedName("ID_CHITIET_CTO_TREO")
    public int ID_CHITIET_CTO_TREO;

    //anh cong to
    @SerializedName("TEN_ANH_CTO_TREO")
    public String TEN_ANH_CTO_TREO;
    @SerializedName("TEN_ANH_NIEMPHONG_CTO_TREO")
    public String TEN_ANH_NIEMPHONG_CTO_TREO;
    @SerializedName("ANH_CTO_TREO")

    public String ANH_CTO_TREO;
    @SerializedName("ANH_NIEMPHONG_CTO_TREO")
    public String ANH_NIEMPHONG_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_CTO_TREO")
    public String CREATE_DAY_ANH_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_NIEMPHONG_CTO_TREO")
    public String CREATE_DAY_ANH_NIEMPHONG_CTO_TREO;


    //anh TU
    @SerializedName("TEN_ANH_TU_CTO_TREO")
    public String TEN_ANH_TU_CTO_TREO;
    @SerializedName("ANH_TU_CTO_TREO")
    public String ANH_TU_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_TU_CTO_TREO")
    public String CREATE_DAY_ANH_TU_CTO_TREO;

    //anh TU mach nhi thu
    @SerializedName("TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_TREO")
    public String TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_TREO;
    @SerializedName("ANH_TU_ANH_MACH_NHI_THU_CTO_TREO")
    public String ANH_TU_ANH_MACH_NHI_THU_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_TREO")
    public String CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_TREO;

    //anh TU mach niem phong
    @SerializedName("TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO")
    public String TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO;
    @SerializedName("ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO")
    public String ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_TREO")
    public String CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_TREO;


    //anh TI
    @SerializedName("TEN_ANH_TI_CTO_TREO")
    public String TEN_ANH_TI_CTO_TREO;
    @SerializedName("ANH_TI_CTO_TREO")
    public String ANH_TI_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_TI_CTO_TREO")
    public String CREATE_DAY_ANH_TI_CTO_TREO;

    //anh TI mach nhi thu
    @SerializedName("TEN_ANH_TI_ANH_MACH_NHI_THU_CTO_TREO")
    public String TEN_ANH_TI_ANH_MACH_NHI_THU_CTO_TREO;
    @SerializedName("ANH_TI_ANH_MACH_NHI_THU_CTO_TREO")
    public String ANH_TI_ANH_MACH_NHI_THU_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_MACH_NHI_THU_TI_CTO_TREO")
    public String CREATE_DAY_ANH_MACH_NHI_THU_TI_CTO_TREO;

    //anh TI mach niem phong
    @SerializedName("TEN_ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO")
    public String TEN_ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO;
    @SerializedName("ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO")
    public String ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO;
    @SerializedName("CREATE_DAY_ANH_MACH_NIEM_PHONG_TI_CTO_TREO")
    public String CREATE_DAY_ANH_MACH_NIEM_PHONG_TI_CTO_TREO;


    //TODO anh Cong To Thao
    @SerializedName("ID_BBAN_TUTI_CTO_THAO")
    public int ID_BBAN_TUTI_CTO_THAO;
    @SerializedName("ID_CHITIET_TUTI_TU_CTO_THAO")
    public int ID_CHITIET_TUTI_TU_CTO_THAO;

    //anh cong to
    @SerializedName("ID_CHITIET_TUTI_TI_CTO_THAO")
    public String ID_CHITIET_TUTI_TI_CTO_THAO;
    @SerializedName("ID_CHITIET_CTO_THAO")
    public int ID_CHITIET_CTO_THAO;

    //anh cong to
    @SerializedName("TEN_ANH_CTO_THAO")
    public String TEN_ANH_CTO_THAO;
    @SerializedName("TEN_ANH_NIEMPHONG_CTO_THAO")
    public String TEN_ANH_NIEMPHONG_CTO_THAO;
    @SerializedName("ANH_CTO_THAO")
    public String ANH_CTO_THAO;
    @SerializedName("ANH_NIEMPHONG_CTO_THAO")
    public String ANH_NIEMPHONG_CTO_THAO;
    @SerializedName("CREATE_DAY_ANH_CTO_THAO")
    public String CREATE_DAY_ANH_CTO_THAO;
    @SerializedName("CREATE_DAY_ANH_NIEMPHONG_CTO_THAO")
    public String CREATE_DAY_ANH_NIEMPHONG_CTO_THAO;

    //anh TU
    @SerializedName("TEN_ANH_TU_CTO_THAO")
    public String TEN_ANH_TU_CTO_THAO;
    @SerializedName("ANH_TU_CTO_THAO")
    public String ANH_TU_CTO_THAO;
    @SerializedName("CREATE_DAY_ANH_TU_CTO_THAO")
    public String CREATE_DAY_ANH_TU_CTO_THAO;

    //anh TU mach nhi thu
    @SerializedName("TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_THAO")
    public String TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_THAO;
    @SerializedName("ANH_TU_ANH_MACH_NHI_THU_CTO_THAO")
    public String ANH_TU_ANH_MACH_NHI_THU_CTO_THAO;
    @SerializedName("CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_THAO")
    public String CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_THAO;

    //anh TU mach niem phong
    @SerializedName("TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO")
    public String TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO;
    @SerializedName("ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO")
    public String ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO;
    @SerializedName("CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_THAO")
    public String CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_THAO;


    public MTBModelNew(
            int ID_BBAN_CONGTO, String MA_DVIQLY, String SO_BBAN, int TRANG_THAI, int LAN_CTO_TREO, int VTRI_TREO_THAO_CTO_TREO, int SOVIEN_CBOOC_CTO_TREO, int LOAI_HOM_CTO_TREO, int SOVIEN_CHOM_CTO_TREO, int HS_NHAN_CTO_TREO, String SO_TU_CTO_TREO, String SO_TI_CTO_TREO, String CHI_SO_CTO_TREO, int CCX_CTO_TREO, String TEM_CQUANG_CTO_TREO, int SOVIEN_CHIKDINH_CTO_TREO, String DIEN_AP_CTO_TREO, String DONG_DIEN_CTO_TREO, String HANGSO_K_CTO_TREO, String SO_KIM_NIEM_CHI_CTO_TREO, String TTRANG_NPHONG_CTO_TREO, String TEN_LOAI_CTO_CTO_TREO, String PHUONG_THUC_DO_XA_CTO_TREO, String GHI_CHU_CTO_TREO, int LAN_CTO_THAO, int VTRI_TREO_THAO_CTO_THAO, int SOVIEN_CBOOC_CTO_THAO,
            int LOAI_HOM_CTO_THAO, int SOVIEN_CHOM_CTO_THAO, int HS_NHAN_CTO_THAO, String SO_TU_CTO_THAO, String SO_TI_CTO_THAO, String CHI_SO_CTO_THAO, int CCX_CTO_THAO, String TEM_CQUANG_CTO_THAO, int SOVIEN_CHIKDINH_CTO_THAO, String DIEN_AP_CTO_THAO, String DONG_DIEN_CTO_THAO, String HANGSO_K_CTO_THAO, String SO_KIM_NIEM_CHI_CTO_THAO, String TTRANG_NPHONG_CTO_THAO, String TEN_LOAI_CTO_CTO_THAO, String PHUONG_THUC_DO_XA_CTO_THAO, String GHI_CHU_CTO_THAO, int ID_BBAN_TUTI_CTO_TREO, int ID_CHITIET_TUTI_TU_CTO_TREO, int ID_CHITIET_TUTI_TI_CTO_TREO, int ID_CHITIET_CTO_TREO, String TEN_ANH_CTO_TREO, String TEN_ANH_NIEMPHONG_CTO_TREO, String ANH_CTO_TREO, String ANH_NIEMPHONG_CTO_TREO, String CREATE_DAY_ANH_CTO_TREO, String CREATE_DAY_ANH_NIEMPHONG_CTO_TREO,
            String TEN_ANH_TU_CTO_TREO, String ANH_TU_CTO_TREO, String CREATE_DAY_ANH_TU_CTO_TREO, String TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_TREO, String ANH_TU_ANH_MACH_NHI_THU_CTO_TREO, String CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_TREO, String TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO, String ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO, String CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_TREO, String TEN_ANH_TI_CTO_TREO, String ANH_TI_CTO_TREO, String CREATE_DAY_ANH_TI_CTO_TREO, String TEN_ANH_TI_ANH_MACH_NHI_THU_CTO_TREO, String ANH_TI_ANH_MACH_NHI_THU_CTO_TREO, String CREATE_DAY_ANH_MACH_NHI_THU_TI_CTO_TREO, String TEN_ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO, String ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO, String CREATE_DAY_ANH_MACH_NIEM_PHONG_TI_CTO_TREO, int ID_BBAN_TUTI_CTO_THAO, int ID_CHITIET_TUTI_TU_CTO_THAO, String ID_CHITIET_TUTI_TI_CTO_THAO, int ID_CHITIET_CTO_THAO, String TEN_ANH_CTO_THAO, String TEN_ANH_NIEMPHONG_CTO_THAO, String ANH_CTO_THAO, String ANH_NIEMPHONG_CTO_THAO, String CREATE_DAY_ANH_CTO_THAO, String CREATE_DAY_ANH_NIEMPHONG_CTO_THAO, String TEN_ANH_TU_CTO_THAO, String ANH_TU_CTO_THAO, String CREATE_DAY_ANH_TU_CTO_THAO, String TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_THAO, String ANH_TU_ANH_MACH_NHI_THU_CTO_THAO, String CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_THAO, String TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO, String ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO, String CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_THAO) {
        this.ID_BBAN_CONGTO = ID_BBAN_CONGTO;
        this.MA_DVIQLY = MA_DVIQLY;
        this.SO_BBAN = SO_BBAN;
        this.TRANG_THAI = TRANG_THAI;
        this.LAN_CTO_TREO = LAN_CTO_TREO;
        this.VTRI_TREO_THAO_CTO_TREO = VTRI_TREO_THAO_CTO_TREO;
        this.SOVIEN_CBOOC_CTO_TREO = SOVIEN_CBOOC_CTO_TREO;
        this.LOAI_HOM_CTO_TREO = LOAI_HOM_CTO_TREO;
        this.SOVIEN_CHOM_CTO_TREO = SOVIEN_CHOM_CTO_TREO;
        this.HS_NHAN_CTO_TREO = HS_NHAN_CTO_TREO;
        this.SO_TU_CTO_TREO = SO_TU_CTO_TREO;
        this.SO_TI_CTO_TREO = SO_TI_CTO_TREO;
        this.CHI_SO_CTO_TREO = CHI_SO_CTO_TREO;
        this.CCX_CTO_TREO = CCX_CTO_TREO;
        this.TEM_CQUANG_CTO_TREO = TEM_CQUANG_CTO_TREO;
        this.SOVIEN_CHIKDINH_CTO_TREO = SOVIEN_CHIKDINH_CTO_TREO;
        this.DIEN_AP_CTO_TREO = DIEN_AP_CTO_TREO;
        this.DONG_DIEN_CTO_TREO = DONG_DIEN_CTO_TREO;
        this.HANGSO_K_CTO_TREO = HANGSO_K_CTO_TREO;
        this.SO_KIM_NIEM_CHI_CTO_TREO = SO_KIM_NIEM_CHI_CTO_TREO;
        this.TTRANG_NPHONG_CTO_TREO = TTRANG_NPHONG_CTO_TREO;
        this.TEN_LOAI_CTO_CTO_TREO = TEN_LOAI_CTO_CTO_TREO;
        this.PHUONG_THUC_DO_XA_CTO_TREO = PHUONG_THUC_DO_XA_CTO_TREO;
        this.GHI_CHU_CTO_TREO = GHI_CHU_CTO_TREO;
        this.LAN_CTO_THAO = LAN_CTO_THAO;
        this.VTRI_TREO_THAO_CTO_THAO = VTRI_TREO_THAO_CTO_THAO;
        this.SOVIEN_CBOOC_CTO_THAO = SOVIEN_CBOOC_CTO_THAO;

        this.LOAI_HOM_CTO_THAO = LOAI_HOM_CTO_THAO;
        this.SOVIEN_CHOM_CTO_THAO = SOVIEN_CHOM_CTO_THAO;
        this.HS_NHAN_CTO_THAO = HS_NHAN_CTO_THAO;
        this.SO_TU_CTO_THAO = SO_TU_CTO_THAO;
        this.SO_TI_CTO_THAO = SO_TI_CTO_THAO;
        this.CHI_SO_CTO_THAO = CHI_SO_CTO_THAO;
        this.CCX_CTO_THAO = CCX_CTO_THAO;
        this.TEM_CQUANG_CTO_THAO = TEM_CQUANG_CTO_THAO;
        this.SOVIEN_CHIKDINH_CTO_THAO = SOVIEN_CHIKDINH_CTO_THAO;
        this.DIEN_AP_CTO_THAO = DIEN_AP_CTO_THAO;
        this.DONG_DIEN_CTO_THAO = DONG_DIEN_CTO_THAO;
        this.HANGSO_K_CTO_THAO = HANGSO_K_CTO_THAO;
        this.SO_KIM_NIEM_CHI_CTO_THAO = SO_KIM_NIEM_CHI_CTO_THAO;
        this.TTRANG_NPHONG_CTO_THAO = TTRANG_NPHONG_CTO_THAO;
        this.TEN_LOAI_CTO_CTO_THAO = TEN_LOAI_CTO_CTO_THAO;
        this.PHUONG_THUC_DO_XA_CTO_THAO = PHUONG_THUC_DO_XA_CTO_THAO;
        this.GHI_CHU_CTO_THAO = GHI_CHU_CTO_THAO;
        this.ID_BBAN_TUTI_CTO_TREO = ID_BBAN_TUTI_CTO_TREO;
        this.ID_CHITIET_TUTI_TU_CTO_TREO = ID_CHITIET_TUTI_TU_CTO_TREO;
        this.ID_CHITIET_TUTI_TI_CTO_TREO = ID_CHITIET_TUTI_TI_CTO_TREO;
        this.ID_CHITIET_CTO_TREO = ID_CHITIET_CTO_TREO;
        this.TEN_ANH_CTO_TREO = TEN_ANH_CTO_TREO;
        this.TEN_ANH_NIEMPHONG_CTO_TREO = TEN_ANH_NIEMPHONG_CTO_TREO;
        this.ANH_CTO_TREO = ANH_CTO_TREO;
        this.ANH_NIEMPHONG_CTO_TREO = ANH_NIEMPHONG_CTO_TREO;
        this.CREATE_DAY_ANH_CTO_TREO = CREATE_DAY_ANH_CTO_TREO;
        this.CREATE_DAY_ANH_NIEMPHONG_CTO_TREO = CREATE_DAY_ANH_NIEMPHONG_CTO_TREO;
        this.TEN_ANH_TU_CTO_TREO = TEN_ANH_TU_CTO_TREO;
        this.ANH_TU_CTO_TREO = ANH_TU_CTO_TREO;
        this.CREATE_DAY_ANH_TU_CTO_TREO = CREATE_DAY_ANH_TU_CTO_TREO;
        this.TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_TREO = TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_TREO;
        this.ANH_TU_ANH_MACH_NHI_THU_CTO_TREO = ANH_TU_ANH_MACH_NHI_THU_CTO_TREO;
        this.CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_TREO = CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_TREO;
        this.TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO = TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO;
        this.ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO = ANH_TU_ANH_MACH_NIEM_PHONG_CTO_TREO;
        this.CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_TREO = CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_TREO;
        this.TEN_ANH_TI_CTO_TREO = TEN_ANH_TI_CTO_TREO;
        this.ANH_TI_CTO_TREO = ANH_TI_CTO_TREO;
        this.CREATE_DAY_ANH_TI_CTO_TREO = CREATE_DAY_ANH_TI_CTO_TREO;
        this.TEN_ANH_TI_ANH_MACH_NHI_THU_CTO_TREO = TEN_ANH_TI_ANH_MACH_NHI_THU_CTO_TREO;
        this.ANH_TI_ANH_MACH_NHI_THU_CTO_TREO = ANH_TI_ANH_MACH_NHI_THU_CTO_TREO;
        this.CREATE_DAY_ANH_MACH_NHI_THU_TI_CTO_TREO = CREATE_DAY_ANH_MACH_NHI_THU_TI_CTO_TREO;
        this.TEN_ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO = TEN_ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO;
        this.ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO = ANH_TI_ANH_MACH_NIEM_PHONG_CTO_TREO;
        this.CREATE_DAY_ANH_MACH_NIEM_PHONG_TI_CTO_TREO = CREATE_DAY_ANH_MACH_NIEM_PHONG_TI_CTO_TREO;
        this.ID_BBAN_TUTI_CTO_THAO = ID_BBAN_TUTI_CTO_THAO;
        this.ID_CHITIET_TUTI_TU_CTO_THAO = ID_CHITIET_TUTI_TU_CTO_THAO;
        this.ID_CHITIET_TUTI_TI_CTO_THAO = ID_CHITIET_TUTI_TI_CTO_THAO;
        this.ID_CHITIET_CTO_THAO = ID_CHITIET_CTO_THAO;
        this.TEN_ANH_CTO_THAO = TEN_ANH_CTO_THAO;
        this.TEN_ANH_NIEMPHONG_CTO_THAO = TEN_ANH_NIEMPHONG_CTO_THAO;
        this.ANH_CTO_THAO = ANH_CTO_THAO;
        this.ANH_NIEMPHONG_CTO_THAO = ANH_NIEMPHONG_CTO_THAO;
        this.CREATE_DAY_ANH_CTO_THAO = CREATE_DAY_ANH_CTO_THAO;
        this.CREATE_DAY_ANH_NIEMPHONG_CTO_THAO = CREATE_DAY_ANH_NIEMPHONG_CTO_THAO;
        this.TEN_ANH_TU_CTO_THAO = TEN_ANH_TU_CTO_THAO;
        this.ANH_TU_CTO_THAO = ANH_TU_CTO_THAO;
        this.CREATE_DAY_ANH_TU_CTO_THAO = CREATE_DAY_ANH_TU_CTO_THAO;
        this.TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_THAO = TEN_ANH_TU_ANH_MACH_NHI_THU_CTO_THAO;
        this.ANH_TU_ANH_MACH_NHI_THU_CTO_THAO = ANH_TU_ANH_MACH_NHI_THU_CTO_THAO;
        this.CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_THAO = CREATE_DAY_ANH_MACH_NHI_THU_TU_CTO_THAO;
        this.TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO = TEN_ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO;
        this.ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO = ANH_TU_ANH_MACH_NIEM_PHONG_CTO_THAO;
        this.CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_THAO = CREATE_DAY_ANH_MACH_NIEM_PHONG_TU_CTO_THAO;
    }
}
